### ISSUE TITLE
Undefined getIntegerTypeDeclaration

### ISSUE THREAD

**Issue by pablomoreno61** [mmerian/doctrine-timestamp#1]
Fatal error: Call to undefined method Doctrine\DBAL\Platforms\MySqlPlatform::getIntegerTypeDeclaration() in /var/www/my-project/vendor/mmerian/doctrine-timestamp/lib/DoctrineTimestamp/DBAL/Types/Timestamp.php on line 34

After a bit of investigation, the easier way is to replace line 34 by:

return self::TIMESTAMP;

**Comment by mmerian** [comment]
Thanks for the report.

After a quick look, I think the call to getIntegerTypeDeclaration() should be replaced with getIntegerTypeDeclarationSQL(). I'll check that a bit more and fix it asap.

**Comment by pablomoreno61** [comment]
I've been checking your change, but it creates the column as an INT column, so it doesn't works neither.. Writing self::TIMESTAMP is the only way I've found for make it work.

**Comment by mmerian** [comment]
The fact that is creates an INT column is the expected behavior. The goal here is to store the timestamps as unix timestamps, which are integers.

Storing timestamps as integers is done to get rid of timezone issues.

The code make the conversions between DateTime and int for you.

**Comment by pablomoreno61** [comment]
You're right, that has sense, but it is weird for me too see it like an INT column in Mysql. In my case, I want to use it in a created_at and updated_at columns, so  I need columns declared like following:

ALTER TABLE [tablename] CHANGE updated_at updated_at timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE [tablename] CHANGE created_at created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL;

If the declaration is integer, we cannot do it, because it's not a real timestamp mysql type.

**Comment by mmerian** [comment]
I understand your need to have timestamp columns auto updated.

For that, you can use lifecycle callbacks in Doctrine : http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/events.html#lifecycle-callbacks

**Comment by pablomoreno61** [comment]
Yes, I've applied it, thanks for the advice!
